[package]
name = "tictacjoe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# cargo run [dev]
# cargo run --release


[dependencies]
# name = "version"